unique_ids:
  assets:
    standard-page.html: SGFVDTDEHTWOI5LQSBC7Y5AYTHJ7VYII
    theme.css: PFJYZZSNWCSRUQUSGBUSYQCLVUEQHBOE
  forms:
    Form1: ADVSDLDIQELHVHCRWOSXOWKT36AW24W7
  modules: {}
  scripts: {}
  server_modules: {}
